require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable # rubocopの新機能をactiveにする
  Exclude:
    - "assets/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "log/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い public class を許可
Style/Documentation:
  Enabled: false

# frozen_string_literal の指定強制を解除
Style/FrozenStringLiteralComment:
  Enabled: false

# 1行の最大
Layout/LineLength:
  Max: 170

# （お好みで設定）文字列はダブルクォートに統一
Style/StringLiterals:
  EnforcedStyle: double_quotes

# （お好みで設定）%w, %i を使用強制を解除（使用しても使用しなくてもOKにする）
Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# コメントアウト可能
Layout/CommentIndentation:
  Enabled: false

# 最大ネスト
RSpec/NestedGroups:
  Max: 10

# 最大expect数
RSpec/MultipleExpectations:
  Enabled: false

# 環境変数の読み込み設定
Rails/EnvironmentVariableAccess:
  AllowReads: true

# 同じ文言の許可
RSpec/ExampleLength:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false