default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /tmp/mysql.sock
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: movie_share_app_development

test:
  <<: *default
  database: movie_share_app_test

production:
  <<: *default
  database: movie_share_app_production
  username: movie_share_app
  password: <%= ENV['DB_PASSWORD'] %>
  